# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce77a3ea9328dfa5869d0ce45dd154a8657168d0b418b84fa36e276bbde4edacd8e963742c3cc6064e709bb7310acdbbdd82ce7d6910a73e1406923671d97b8f

test:
  secret_key_base: 65b1974b841f40296918384e7017ab9c433cefef6d28d31676c16c0268d20bb43e53ae2686a4d18f54a6894e6afe03547fce0d71140fab7d8b7d09e2bee6a8eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
